name: backup_tool
description: The app part of the BackupTool project made with Flutter and Rust
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Work Sans
    fonts:
      - asset: assets/fonts/WorkSans.ttf
      - asset: assets/fonts/WorkSans-Italic.ttf
        style: italic