name: drive_explorer
description: Yet another google drive explorer
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  googleapis: ^9.2.0
  url_launcher: ^6.1.7
  googleapis_auth: ^1.3.1
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  flutter_secure_storage: ^7.0.1
  syncfusion_flutter_charts: ^20.4.42
  go_router: ^6.0.1
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Work Sans
    fonts:
      - asset: assets/fonts/WorkSans.ttf
      - asset: assets/fonts/WorkSans-Italic.ttf
        style: italic
  assets:
  - .env